version: '3.8'

services:
  stock_tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    image: stock_tracker
    container_name: stock_tracker_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./go_stock-tracker/.token.json:/app/.token.json

  postgres:
    image: postgres:15-alpine
    container_name: stock_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypissword
      POSTGRES_DB: stock_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
    driver: local